apiVersion: v1
kind: Service
metadata:
    name: my-service 
    labels:
        app: myweb-service 
spec:
    selector:
        app: myweb-app 
    type: ClusterIP
    ports:
     -  port: 81
        targetPort: 80
