apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-pvc1
    labels:
        name: dbpvc1
spec:
    accessModes:
     -  ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

