apiVersion: v1
kind: Service
metadata:
    name: my-service 
    labels:
        app: myweb-service 
spec:
    selector:
        app: myweb-app 
    type: NodePort
    ports:
     - nodePort: 31000
       port: 80
       targetPort: 80
