apiVersion: v1
kind: Pod
metadata:
    name: mywebpod
    labels:
        app: myweb-app 

spec:
    containers:
     -  name: mywebcon
        image: vimal13/apache-webserver-php
        ports:
         -  containerPort: 80
