apiVersion: v1
kind: Pod
metadata:
    name: mywebpod
    labels:
        env: production
spec:
    containers:
     -  name: mywebcon
        image: httpd
        volumeMounts:
         -  name: web-vol1
            mountPath: /var/www/html
    volumes:
     -  name: web-vol1 
        persistentVolumeClaim:
            claimName: web-pvc1

