apiVersion: v1
kind: PersistentVolume
metadata:
    name: mywebpv
spec:
    capacity:
        storage: 5Gi
    volumeMode: Filesystem
    accessModes:
     -  ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: slow
    mountOptions:
     -  hard
     -  nfservers=4.1
    nfs:
        path: /tmp 
        server: 172.17.0.2
