apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc1
    
spec:
    replicas: 3
    selector:
        env: production
    template:
        metadata:
            name: myweb-pod
            labels:
                env: production
        spec:
            containers:
              - name: mywebcon1
                image: vimal13/apache-webserver-php



