apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myrs1

spec:
    replicas: 3
    selector:
        matchExpressions:
          - { key: env, operator: In, values: [production ] }
          - { key: region, operator: In, values: [IN ] }
    template:
        metadata:
            name: mywebpod
            labels:
                env: production
                region: IN 
                dc: "2"
        spec:
            containers:
              - name: myrscon
                image: vimal13/apache-webserver-php


