apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myrs1
    labels:
        env: production

spec:
    replicas: 3
    selector: 
        matchLabels:
            env: production 
    template:
        metadata:
            name: mywebpod
            labels:
                env: production
                region: IN 
                dc: "2"
        spec:
            containers:
              - name: myrscon
                image: vimal13/apache-webserver-php


